### ISSUE TITLE
Client not opening via Debug // System.IndexOutofRangeException

### ISSUE THREAD

**Issue by Adarian** [Deathly/TerrariaAPI#16]
When I try to debug after commenting out the Steam code in the Program.cs, the client simply still doesn't open or show any effort to open or print an error. The debug green button greys out as if debugging has begun, but then a second later it restores.
I thought this could just be a debugging issue, so I built the project then copied the Terraria.exe over to my main game directory and tried it out, and I received this error:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Main.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.Main(String[] args)

Note that this is without any added classes or modding.

-Adarian

**Comment by ghost** [comment]
https://github.com/Deathly/TerrariaAPI/wiki/%5BTutorial%5D-0.-Decompiling-Terraria
4th from the bottom

**Comment by Adarian** [comment]
Hm I saw that but didn't think it would be relevant to my error.
Alas, it worked anyway.
Cheers.

-Adarian
