### ISSUE TITLE
Give Item  Command ?

### ISSUE THREAD

**Issue by fortunez** [Deathly/TerrariaAPI#2]
I Get loads of error's while putting in the code, Most of them are Do not exist ones like Var - "The namespace "var" could not be found?
same with main,text,if, etc? anyone got a fix? :) got the others to work like hooking chat + single player chat

**Comment by diede** [comment]
Looks like you are not in a namespace, you need some understanding of C# if you want to do the more complex things.
It should work if you just put the code inside the hooking chat, the onChat method in ModClass.cs
If you can't fix it you can send your ModClass.cs to me and I'll explain what is wrong in-depth.
contact me at diede@apers.net

Good luck,
Diede
