### ISSUE TITLE
New errors in 1.0.4

### ISSUE THREAD

**Issue by hansihe** [Deathly/TerrariaAPI#5]
In 1.0.4 there is some new errors after decompiling.
"Use of unassigned local variable strArray2" and "Use of unassigned local variable strArray3".
I tried to find a way to fix it, but i am just learning and not a good c# coder.
Any help would be appriciated!

**Comment by Deathly** [comment]
I really like to help people.
But if they are just too damn blind to even read the tutorials I do not feel like helping them..

PLEASE JUST READ THE DAMN TUTORIAL ITS ALL DESCRIBED IN THERE!

**Comment by hansihe** [comment]
Im really sorry if im dumb or stupid or anything, but i followed the tutorial word for word, and i suceeded in 1.0.3. However in 1.0.4 those two errors dint get fixed by any of the approches in the tutorial.

**Comment by Deathly** [comment]
That is impossible. You must have done something wrong.

Others got it working, so it must be your fault.

Also that code didn't change and there is no way for it not to work anymore.
