### ISSUE TITLE
1.0.4 Issues: No MOB Spawn

### ISSUE THREAD

**Issue by Naddox** [Deathly/TerrariaAPI#6]
My friend and I have decompiled 1.0.4 and fixed all the errors and crashes to the letter of your tutorial but now we notice that in our worlds, no monsters spawn?

So just to be sure I didnt make some mistake of sorts, I did a complete reinstall of terraria, and did a freash decompile and went through all the steps again and still no mobs spawn. The sources are still clean and have not been modded.

EDIT: The guide is still there though, just incase you needed to know.

**Comment by Naddox** [comment]
Why'd you close it when the issue isnt resolved?

**Comment by Deathly** [comment]
Sorry,

someone told me to close it and I had no time to look at it.

**Comment by Naddox** [comment]
Oh ok gotcha

**Comment by AnimeZer0** [comment]
I've got the same problem, is there no way to fix this?
Isn't there some kind of problem in the code after extracting it that sets the max allowed spawns to 0 or something?
Making 'Mods' is pointless if Mobs don't spawn..

**Comment by Naddox** [comment]
This fixes it
https://github.com/Deathly/TerrariaAPI/issues/12
