### ISSUE TITLE
Is there any way to remove player items in Multiplayer?

### ISSUE THREAD

**Issue by ioptional** [Deathly/TerrariaAPI#8]
```
        for (int i = 0; i < Main.player[Player].inventory.Length; i++)
        {
            Main.player[Player].inventory[i] = new Item();
        }
```

It just only updating server side data instead of client side?

**Comment by Deathly** [comment]
Are you modding the client or the server here?

Afaik the inventory is totally client side. It gets sent to the server, but there is no way to modify it.
